// Get API Endpoint from json generated by CDK deployment

const fileName = "./data.json"

async function getData(fileName) {
    const response = await fetch(fileName);
    return response.json();
}
  
const file = await getData(fileName);
  
const API_ENDPOINT = file.API_ENDPOINT

// Setup divs that will be used to display interactive messages
var errorDiv = document.getElementById('error-message')
var successDiv = document.getElementById('success-message')
var resultsDiv = document.getElementById('results-message')

// Setup easy way to reference values of the input boxes
function messageValue() { return document.getElementById('message').value }
function emailValue() { return document.getElementById('email').value }
function phoneValue() { return document.getElementById('phone').value }
function waitSecondsValue() { return document.getElementById('waitSeconds').value }

function clearNotifications() {
    // Clear any exisiting notifications in the browser notifications divs
    errorDiv.textContent = '';
    resultsDiv.textContent = '';
    successDiv.textContent = '';
}

// Add listeners for each button that make the API request
document.getElementById('bothButton').addEventListener('click', function(e) {
    sendData(e, 'both');
});

document.getElementById('emailButton').addEventListener('click', function(e) {
    sendData(e, 'email');
});

document.getElementById('smsButton').addEventListener('click', function(e) {
    sendData(e, 'sms');
});

function sendData (e, pref) {
    // Prevent the page reloading and clear exisiting notifications
    e.preventDefault()
    clearNotifications()
    
    // Prepare the appropriate HTTP request to the API with fetch
    // create uses the root /prometheon endpoint and requires a JSON payload
    fetch(API_ENDPOINT, {
        headers: {
            "Content-type": "application/json"
        },
        method: 'POST',
        body: JSON.stringify({
            waitSeconds: waitSecondsValue(),
            preference: pref,
            message: messageValue(),
            email: emailValue(),
            phone: phoneValue()
        }),
        mode: 'cors' // no-cors works but it gives syntax error
    })
    .then(resp => resp.json())
    .then(resp => console.log(resp))
    .then(function(data) {
        successDiv.textContent = 'Looks ok. But check the result below!';
        resultsDiv.textContent = JSON.stringify(data);
    })
    .catch(function(err) {
        errorDiv.textContent = 'Yikes! There was an error:\n' + err.toString();
        console.log(err)
    });
};
